// TEMPORARY NEGATIVE CONTROL - DO NOT MERGE, DO NOT KEEP.
//
// This comment block is the ENTIRE content of branch w1-ctrl-1796. It
// exists only so that this path matches the `cicchetto/e2e/**` entry in
// .github/workflows/integration.yml, which is what makes the integration
// suite run at all. `integration.yml` carries no `workflow_dispatch`, so
// a pull request is the only way to schedule that suite on demand.
//
// WHY. The red-versus-green comparison behind issue 1796 on PR 1886 is
// three reruns of ONE run id against eight runs spread over other days
// and other runner pools. That design cannot separate "the branch" from
// "this pool, this hour". This branch supplies the missing negative
// control: the origin/main tree, unmodified in behaviour, measured in
// the same pool and the same hour as the arm it is compared against.
//
// Nothing below is touched. Remove this block and the branch with it.

import { defineConfig, devices } from "@playwright/test";

// Grappa e2e Playwright config.
//
// TAG VOCABULARY — ONE TAG IS ONE PROJECT OPT-IN (issue 1878):
//
//     @webkit  -> also runs on `webkit-iphone-15`
//     @touch   -> also runs on `chromium-pixel-touch`
//     both     -> runs on BOTH
//     neither  -> runs on `chromium`, the desktop default
//
// The two tags are ORTHOGONAL, not a partition. A mobile behaviour that has
// to hold on two engines carries BOTH, which is what issue 1878 did to the
// mobile suite: every `@webkit` entry that is not iOS-bound gained `@touch`
// alongside it rather than in place of it. Read a tag as "which project",
// never as "which platform the behaviour is about" — a spec keeps its
// `@webkit` when it gains `@touch`, so `--grep @webkit` still collects
// exactly what it collected before, and the eight iOS-bound entries that
// hold `@webkit` alone (six assert `html.is-ios` is PRESENT and read the
// cascade hanging off it, two ride `navigator.standalone`) are the only
// ones the widening skipped. Their Android twins are separate test code,
// not a retag.
//
// 🔴 Why ORTHOGONAL and not "@touch means mobile, on both projects", which
// is what issue 1878 proposed: `@touch` already existed, meaning
// chromium-only, and two specs rely on that. Widening
// `webkit-iphone-15` to `grep: /@webkit|@touch/` would drag
// `issue1869-android-longpress-selection.spec.ts` onto WebKit, where its
// `expect(standing?.isIos).toBe(false)` is false by construction — a RED,
// not a vacuous green — and would drag `issue1831-tap-send-modal-survives`
// onto the one engine its own header forbids in capitals, having measured
// that the pre-cure code passes there. Orthogonal tags need no such
// exception, and cost no config change at all.
//
// Base URL is wired via E2E_BASE_URL — set on the playwright-runner
// container in cicchetto/e2e/compose.yaml. Local-host runs need to
// export it manually (or hit nginx-test directly when on the docker
// network).
//
// Push notifications cluster B5 (2026-05-14) — switched the e2e
// surface from `http://nginx-test` to `https://nginx-test` so the
// cic SW + Push API + Notification API have a secure context to
// register against (W3C requires `isSecureContext` for these). The
// nginx-test container's :443 listener uses a throwaway self-signed
// cert generated by nginx-certs/gen-cert.sh; Playwright's
// `ignoreHTTPSErrors: true` accepts it without prompting. The :80
// listener stays alive for legacy spec compatibility — specs that
// don't need push can keep hitting plain HTTP via E2E_BASE_URL
// override (only one suite-wide baseURL is set today; per-spec
// override via `test.use({ baseURL: ... })` if a spec ever needs
// the HTTP surface specifically).

const baseURL = process.env.E2E_BASE_URL ?? "https://nginx-test";

export default defineConfig({
  testDir: "./tests",
  globalSetup: "./fixtures/seedData.ts",
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: 1,
  // `./reporters/coldStart.ts` (#1584) — LAST on purpose, so its census
  // prints under the list summary rather than above the first test line.
  // A reporter, not a fixture: it is the only place that sees every test's
  // true worker and true order, including the 29 spec files that import
  // `test` from `@playwright/test` and so are invisible to `fixtures/test`.
  reporter: [
    ["list"],
    ["html", { outputFolder: "playwright-report", open: "never" }],
    ["./reporters/coldStart.ts"],
  ],
  use: {
    baseURL,
    // Self-signed nginx-test cert — accepted across every spec.
    // Push specs *require* this to be true; non-push specs are
    // unaffected.
    ignoreHTTPSErrors: true,
    trace: "retain-on-failure",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        // Push notifications cluster B5 (2026-05-14) — chromium's
        // service-worker subsystem uses a SEPARATE TLS validation
        // path that Playwright's `ignoreHTTPSErrors` doesn't affect.
        // SW registration against the self-signed nginx-test cert
        // fails with "An SSL certificate error occurred when
        // fetching the script" without this flag. Test-only cert
        // issued by nginx-certs/gen-cert.sh, throwaway.
        launchOptions: {
          args: ["--ignore-certificate-errors"],
        },
      },
      // The complement of the two touch projects' greps: a spec that has
      // opted into either of them does NOT also run here. Without this
      // gate a touch-tagged spec attempts `tap()` on a non-touch context
      // and throws "The page does not support tap".
      //
      // It must name EVERY touch project's tag, so a fourth project means
      // an edit here as well — that coupling is the price of the desktop
      // project being defined by subtraction, and it is deliberate: the
      // alternative is tagging ~650 desktop entries.
      grepInvert: /@webkit|@touch/,
    },
    {
      // issue 1831 — the ONLY project whose touch produces the compat mouse
      // events a real tap produces. Measured, because it is the whole reason
      // this project exists: on `webkit-iphone-15` a `tap()` dispatches
      // `pointerdown / touchstart / pointerup` and STOPS — no touchend, no
      // mousedown/mouseup, no click at all — so a spec about what a
      // synthesised click hits is unanswerable there and goes green whatever
      // the code does. On chromium + touch the same tap dispatches all six,
      // and the click hit-tests against the layout as it stands THEN.
      //
      // Also the closer engine family to the reported device (Android), though
      // that device runs Gecko and this is Blink — see the spec header.
      //
      // `grep: /@touch/` collects the MOBILE suite, never the whole suite.
      // Issue 1878 widened what that means — from the handful of specs that
      // needed a synthesised click to every mobile entry that is not
      // iOS-bound — because a mobile spec running on one engine says "you
      // did not break Safari", not "the mobile UI works". #1869 (a long-press
      // opening two menus on Android) is the shape of bug the old partition
      // left uncovered: the behaviour was gated on `html.is-ios`, which
      // simply is not there off Safari.
      //
      // The device stays `Pixel 7` rather than the `Pixel 5` issue 1878
      // names. Both are chromium with `isMobile` + `hasTouch`; churning it
      // would re-measure every geometry assertion to buy nothing.
      //
      // 🔴 WHAT THIS PROJECT IS NOT, now that it carries the mobile suite and
      // the overclaim gets cheap: a Pixel device descriptor is CHROMIUM with
      // `isMobile` + `hasTouch`. It is not an Android WebView, and it is not
      // Firefox Android. It covers the #1869 family — behaviour gated on
      // `html.is-ios`, which silently vanishes off Safari. It would NOT have
      // caught #717, where Firefox Android hung on the splash of an installed
      // PWA, because Playwright's firefox has no touch emulation and Gecko is
      // not reachable from this harness at all. "Runs on chromium-mobile" is
      // the claim; "Android coverage" is not.
      name: "chromium-pixel-touch",
      use: {
        ...devices["Pixel 7"],
        // Same self-signed nginx-test cert story as the desktop project.
        launchOptions: { args: ["--ignore-certificate-errors"] },
      },
      grep: /@touch/,
    },
    {
      name: "webkit-iphone-15",
      use: { ...devices["iPhone 15"] },
      grep: /@webkit/,
    },
  ],
});
