import { defineConfig, devices } from "@playwright/test";

// Grappa e2e Playwright config.
//
// Default browser project: chromium. iOS-shaped specs (M3, M6, BUG7)
// opt in to webkit + iPhone 15 device via the @webkit tag.
//
// Base URL is wired via E2E_BASE_URL — set on the playwright-runner
// container in cicchetto/e2e/compose.yaml. Local-host runs need to
// export it manually (or hit nginx-test directly when on the docker
// network).
//
// Push notifications cluster B5 (2026-05-14) — switched the e2e
// surface from `http://nginx-test` to `https://nginx-test` so the
// cic SW + Push API + Notification API have a secure context to
// register against (W3C requires `isSecureContext` for these). The
// nginx-test container's :443 listener uses a throwaway self-signed
// cert generated by nginx-certs/gen-cert.sh; Playwright's
// `ignoreHTTPSErrors: true` accepts it without prompting. The :80
// listener stays alive for legacy spec compatibility — specs that
// don't need push can keep hitting plain HTTP via E2E_BASE_URL
// override (only one suite-wide baseURL is set today; per-spec
// override via `test.use({ baseURL: ... })` if a spec ever needs
// the HTTP surface specifically).

const baseURL = process.env.E2E_BASE_URL ?? "https://nginx-test";

export default defineConfig({
  testDir: "./tests",
  globalSetup: "./fixtures/seedData.ts",
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: 1,
  reporter: [
    ["list"],
    ["html", { outputFolder: "playwright-report", open: "never" }],
  ],
  use: {
    baseURL,
    // Self-signed nginx-test cert — accepted across every spec.
    // Push specs *require* this to be true; non-push specs are
    // unaffected.
    ignoreHTTPSErrors: true,
    trace: "retain-on-failure",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        // Push notifications cluster B5 (2026-05-14) — chromium's
        // service-worker subsystem uses a SEPARATE TLS validation
        // path that Playwright's `ignoreHTTPSErrors` doesn't affect.
        // SW registration against the self-signed nginx-test cert
        // fails with "An SSL certificate error occurred when
        // fetching the script" without this flag. Test-only cert
        // issued by nginx-certs/gen-cert.sh, throwaway.
        launchOptions: {
          args: ["--ignore-certificate-errors"],
        },
      },
      // Mirror of webkit-iphone-15's grep — only specs WITHOUT
      // `@webkit` run on the desktop project. Without this gate,
      // `@webkit`-tagged specs (BUG7 + variants) attempt `tap()` on a
      // non-touch context and throw "The page does not support tap".
      grepInvert: /@webkit/,
    },
    {
      name: "webkit-iphone-15",
      use: { ...devices["iPhone 15"] },
      grep: /@webkit/,
    },
  ],
});
