#!/bin/sh
# Install the grappa-source-alias privilege wrapper (#543/#609/#610) and
# render its prefix scope from the DB.
#
# Runs as ROOT inside the jail. Idempotent by construction — a copy, a
# chmod and a rendered config file — which is what lets the deploy run it
# on EVERY path (hot AND cold) instead of only when something is
# classified as needing a restart.
#
# #646 — this used to live inside jail_install_rcd.sh, which the deploy
# only invokes from substrate_restart, i.e. on COLD. No Preflight class
# covers `infra/freebsd/bin/*`, so a wrapper-only change classifies HOT
# and the installer never ran: shipping #610 (whose `arm_check` calls the
# new `probe` subcommand) left the pre-#610 wrapper installed, every probe
# exited 64, mode 2 disarmed, and 44 visitors were rejected in production.
#
# The cure is RECONCILIATION, not classification. Widening the cold
# classification would (a) pay a full session drop to copy one file and
# (b) still miss the other half of the incident: the config file is
# derived from the DB, not from a changed path, so no file-based verdict
# can ever detect that it drifted. Running this every deploy makes the
# installed artifacts a function of the checkout + the DB, full stop.
#
# Invoke by hand (fresh jail, or after editing the wrapper in place):
#   sudo bastille cmd grappa /home/grappa/grappa/infra/freebsd/jail_install_source_alias.sh

set -eu

REPO_ROOT="${REPO_ROOT:-/home/grappa/grappa}"
ENV_FILE="${ENV_FILE:-/usr/local/etc/grappa/grappa.env}"

SA_SRC="${REPO_ROOT}/infra/freebsd/bin/grappa-source-alias"
SA_DST="${SA_DST:-/usr/local/sbin/grappa-source-alias}"
SA_CONF="${SA_CONF:-/usr/local/etc/grappa/source-alias.conf}"

echo "[install_source_alias] copying ${SA_SRC} -> ${SA_DST}"
install -o root -g wheel -m 0555 "${SA_SRC}" "${SA_DST}"

# The wrapper reads its privilege SCOPE — the prefix it may alias inside, and
# refuses to alias outside of — from a root-owned config file, and fails
# closed without it. That prefix MUST equal ServerSettings'
# `addressing.static_mapping_prefix`: a drift does not misbehave quietly, it
# refuses the arm probe with exit 65, i.e. it surfaces as an outage. Render it
# from the DB so the two cannot be kept in sync by hand.
#
# No prefix in the DB (mode 1, or a fresh install) → leave any existing file
# alone rather than truncate it: in that configuration the wrapper is never
# invoked, and a half-written scope is worse than a stale one.
# shellcheck source=/dev/null  # runtime env file, not in the repo
DB_PATH=$(. "${ENV_FILE}" 2>/dev/null; printf '%s' "${DATABASE_PATH:-}")
SA_PREFIX=""

if [ -n "${DB_PATH}" ] && [ -r "${DB_PATH}" ]; then
	SA_PREFIX=$(sqlite3 "file:${DB_PATH}?mode=ro" \
		"select value from server_settings where key='addressing.static_mapping_prefix';" \
		2>/dev/null || true)
fi

if [ -n "${SA_PREFIX}" ]; then
	echo "[install_source_alias] rendering ${SA_CONF} (PREFIX=${SA_PREFIX})"
	mkdir -p "$(dirname "${SA_CONF}")"
	SA_TMP="${SA_CONF}.new.$$"
	printf '# Auto-generated by jail_install_source_alias.sh from the DB prefix. Do not edit.\nPREFIX=%s\n' \
		"${SA_PREFIX}" > "${SA_TMP}"
	install -o root -g wheel -m 0444 "${SA_TMP}" "${SA_CONF}"
	rm -f "${SA_TMP}"
else
	echo "[install_source_alias] no static_mapping_prefix in the DB — leaving ${SA_CONF} as-is"
fi
