#!/bin/sh
# Install the grappa rc.d wrappers + enable + start.
#
# Installs:
#   - grappa                    (BEAM release)
#   - grappa_ndp_keepalive      (v6 source-address NDP keepalive)
#
# Invoke from m42 host:
#   sudo bastille cmd grappa /home/grappa/grappa/infra/freebsd/jail_install_rcd.sh
#
# Idempotent — re-run after `git pull` to refresh the rc.d scripts.

set -eu

REPO_ROOT="/home/grappa/grappa"
ENV_FILE="/usr/local/etc/grappa/grappa.env"

# ── grappa (BEAM release) ──────────────────────────────────────────────
RC_SRC="${REPO_ROOT}/infra/freebsd/rc.d/grappa"
RC_DST="/usr/local/etc/rc.d/grappa"
RC_CONF="/etc/rc.conf.d/grappa"

echo "[install_rcd] copying ${RC_SRC} -> ${RC_DST}"
install -o root -g wheel -m 0555 "${RC_SRC}" "${RC_DST}"

if [ ! -f "${RC_CONF}" ]; then
	echo "[install_rcd] writing ${RC_CONF}"
	cat > "${RC_CONF}" <<EOF
# Auto-generated by jail_install_rcd.sh. Edit by hand if you need to
# move the release elsewhere or run as a different user.
grappa_enable="YES"
grappa_user="grappa"
grappa_release_root="${REPO_ROOT}/_build/prod/rel/grappa"
grappa_env_file="${ENV_FILE}"
EOF
	chmod 0644 "${RC_CONF}"
else
	echo "[install_rcd] ${RC_CONF} already exists — leaving in place"
fi

# ── grappa_ndp_keepalive (v6 NDP keepalive) ────────────────────────────
NDP_RC_SRC="${REPO_ROOT}/infra/freebsd/rc.d/grappa_ndp_keepalive"
NDP_RC_DST="/usr/local/etc/rc.d/grappa_ndp_keepalive"
NDP_RC_CONF="/etc/rc.conf.d/grappa_ndp_keepalive"
NDP_LOOP_SRC="${REPO_ROOT}/infra/freebsd/ndp_keepalive.sh"

echo "[install_rcd] copying ${NDP_RC_SRC} -> ${NDP_RC_DST}"
install -o root -g wheel -m 0555 "${NDP_RC_SRC}" "${NDP_RC_DST}"

echo "[install_rcd] chmod +x ${NDP_LOOP_SRC}"
chmod 0555 "${NDP_LOOP_SRC}"

if [ ! -f "${NDP_RC_CONF}" ]; then
	echo "[install_rcd] writing ${NDP_RC_CONF}"
	cat > "${NDP_RC_CONF}" <<EOF
# Auto-generated by jail_install_rcd.sh.
grappa_ndp_keepalive_enable="YES"
grappa_ndp_keepalive_env_file="${ENV_FILE}"
grappa_ndp_keepalive_interval="10"
grappa_ndp_keepalive_count="3"
# In shared-IP bastille jails `route get default` returns nothing
# (the host owns routing). Pin the upstream gateway here.
grappa_ndp_keepalive_gateway="fe80::1%vtnet0"
EOF
	chmod 0644 "${NDP_RC_CONF}"
else
	echo "[install_rcd] ${NDP_RC_CONF} already exists — leaving in place"
fi

# ── status ─────────────────────────────────────────────────────────────
echo "[install_rcd] service grappa status:"
service grappa status || true

echo "[install_rcd] service grappa_ndp_keepalive status:"
service grappa_ndp_keepalive status || true

echo "[install_rcd] done."
echo "[install_rcd]   start grappa with:                service grappa start"
echo "[install_rcd]   start ndp keepalive with:         service grappa_ndp_keepalive start"
