#!/bin/sh
# Install the grappa rc.d wrapper + enable + start.
#
# Invoke from m42 host:
#   sudo bastille cmd grappa /home/grappa/grappa/infra/freebsd/jail_install_rcd.sh
#
# Idempotent — re-run after `git pull` to refresh the rc.d script.

set -eu

REPO_ROOT="/home/grappa/grappa"
RC_SRC="${REPO_ROOT}/infra/freebsd/rc.d/grappa"
RC_DST="/usr/local/etc/rc.d/grappa"
RC_CONF="/etc/rc.conf.d/grappa"
ENV_FILE="/usr/local/etc/grappa/grappa.env"

echo "[install_rcd] copying ${RC_SRC} -> ${RC_DST}"
install -o root -g wheel -m 0555 "${RC_SRC}" "${RC_DST}"

if [ ! -f "${RC_CONF}" ]; then
	echo "[install_rcd] writing ${RC_CONF}"
	cat > "${RC_CONF}" <<EOF
# Auto-generated by jail_install_rcd.sh. Edit by hand if you need to
# move the release elsewhere or run as a different user.
grappa_enable="YES"
grappa_user="grappa"
grappa_release_root="${REPO_ROOT}/_build/prod/rel/grappa"
grappa_env_file="${ENV_FILE}"
EOF
	chmod 0644 "${RC_CONF}"
else
	echo "[install_rcd] ${RC_CONF} already exists — leaving in place"
fi

echo "[install_rcd] service grappa status:"
service grappa status || true

echo "[install_rcd] done. Start with: service grappa start"
