defmodule Grappa.UploadFixtures do
  @moduledoc """
  Committed binary fixtures for upload + metadata-strip tests.

  The files live in `test/support/fixtures/uploads/` and are
  regenerated by `generate.sh` in that directory (needs exiftool +
  ffmpeg — both in the container image). Each fixture carries
  metadata in the spot the corresponding real-world device writes
  it, so the strip tests assert against the actual leak shape:

    * `:gps_jpeg` — EXIF APP1 with GPS + Make/Model (iPhone photo).
    * `:gps_png` — same EXIF, in the PNG `eXIf` chunk.
    * `:gps_mp4` — QuickTime `udta` `loci`/`©xyz` + `mdta` Keys
      (`com.apple.quicktime.location.ISO6709`) — the three spots
      Apple devices write GPS to.
    * `:tagged_webm` — Matroska Title/Comment. exiftool cannot
      write Matroska, so this pins the ffmpeg-remux strip path.

  Marker strings for presence/absence assertions are exposed via
  `markers/1` so the tests and the fixture stay in lockstep: a test
  asserts the marker IS in the fixture bytes (guards fixture rot)
  and is NOT in the stripped output.
  """

  @fixtures_dir Path.expand("fixtures/uploads", __DIR__)

  @type name :: :gps_jpeg | :gps_png | :gps_mp4 | :gps_mov | :tagged_webm

  @spec bytes(name()) :: binary()
  def bytes(name), do: File.read!(Path.join(@fixtures_dir, file_for(name)))

  @spec mime(name()) :: String.t()
  def mime(:gps_jpeg), do: "image/jpeg"
  def mime(:gps_png), do: "image/png"
  def mime(:gps_mp4), do: "video/mp4"
  def mime(:gps_mov), do: "video/quicktime"
  def mime(:tagged_webm), do: "video/webm"

  @doc """
  Byte sequences that prove metadata presence. Every marker appears
  verbatim in the fixture and must be absent from stripped output.
  """
  @spec markers(name()) :: [binary()]
  def markers(:gps_jpeg), do: ["Exif", "Apple", "iPhone 15 Pro"]
  def markers(:gps_png), do: ["eXIf", "Apple"]
  def markers(:gps_mp4), do: ["com.apple.quicktime", "+41.9028+012.4964", "Apple"]
  def markers(:gps_mov), do: ["com.apple.quicktime", "Apple"]
  def markers(:tagged_webm), do: ["secret title", "GPS 41.9028,12.4964"]

  @doc """
  Assert every metadata marker for `name` is PRESENT in `binary` —
  the fixture-rot guard: a regenerated fixture that lost its
  metadata would otherwise make absence assertions pass while
  validating nothing.
  """
  @spec assert_markers!(binary(), name()) :: :ok
  def assert_markers!(binary, name) when is_binary(binary) do
    Enum.each(markers(name), fn marker ->
      if :binary.match(binary, marker) == :nomatch do
        raise ExUnit.AssertionError,
          message: "fixture #{name} lost its #{inspect(marker)} marker — regenerate it"
      end
    end)

    :ok
  end

  @doc """
  Assert every metadata marker for `name` is ABSENT from `binary` —
  the post-strip check, shared by the unit, context, and door-level
  suites so the marker contract lives in one place.
  """
  @spec refute_markers!(binary(), name()) :: :ok
  def refute_markers!(binary, name) when is_binary(binary) do
    Enum.each(markers(name), fn marker ->
      if :binary.match(binary, marker) != :nomatch do
        raise ExUnit.AssertionError,
          message: "marker #{inspect(marker)} (#{name}) survived the strip"
      end
    end)

    :ok
  end

  defp file_for(:gps_jpeg), do: "gps.jpg"
  defp file_for(:gps_png), do: "gps.png"
  defp file_for(:gps_mp4), do: "gps.mp4"
  defp file_for(:gps_mov), do: "gps.mov"
  defp file_for(:tagged_webm), do: "tagged.webm"
end
