// Generates src/keyboard/emoji-data.ts from unicode-emoji-json.
// Run: scripts/bun.sh run gen:emoji
//
// unicode-emoji-json default export (data-by-emoji.json) is a map:
//   emoji char -> { name, slug, group, emoji_version, unicode_version, skin_tone_support }
//
// Groups in v0.9.0: Smileys & Emotion, People & Body, Animals & Nature,
// Food & Drink, Activities, Travel & Places, Objects, Symbols, Flags.
// (No "Component" group in this version — skin-tone modifiers are omitted.)
//
// We bucket into 8 iOS-style categories, merging "Smileys & Emotion" +
// "People & Body" into one "Smileys & People" tab as iOS does.

import { join } from "node:path";
import emojiData from "unicode-emoji-json";

type Meta = { name: string; group: string };
const data = emojiData as Record<string, Meta>;

// iOS category order → the unicode-emoji-json groups that feed each.
const CATEGORIES: { id: string; label: string; groups: string[] }[] = [
  {
    id: "smileys",
    label: "Smileys & People",
    groups: ["Smileys & Emotion", "People & Body"],
  },
  { id: "animals", label: "Animals & Nature", groups: ["Animals & Nature"] },
  { id: "food", label: "Food & Drink", groups: ["Food & Drink"] },
  { id: "activity", label: "Activities", groups: ["Activities"] },
  { id: "travel", label: "Travel & Places", groups: ["Travel & Places"] },
  { id: "objects", label: "Objects", groups: ["Objects"] },
  { id: "symbols", label: "Symbols", groups: ["Symbols"] },
  { id: "flags", label: "Flags", groups: ["Flags"] },
];

const buckets: Record<string, string[]> = {};
for (const c of CATEGORIES) buckets[c.id] = [];

for (const [char, meta] of Object.entries(data)) {
  const cat = CATEGORIES.find((c) => c.groups.includes(meta.group));
  if (cat) {
    buckets[cat.id]?.push(char);
  } else {
    // Be loud about anything we drop: an upstream group rename (or a
    // returning "Component" group) must not silently shrink the dataset.
    console.warn(`WARN: unrecognized group "${meta.group}" for ${char} — skipped`);
  }
}

// Sanity check before writing.
for (const c of CATEGORIES) {
  const count = buckets[c.id]?.length ?? 0;
  if (count === 0) {
    console.error(
      `ERROR: category "${c.id}" is empty — group strings may not match the installed package version.`,
    );
    process.exit(1);
  }
  console.log(`  ${c.id}: ${count} emojis`);
}

const total = CATEGORIES.reduce((n, c) => n + (buckets[c.id]?.length ?? 0), 0);
console.log(`  total: ${total}`);

const body = `// GENERATED by scripts/gen-emoji.ts — do not edit by hand.
// Source: unicode-emoji-json v0.9.0. Regenerate: scripts/bun.sh run gen:emoji

export interface EmojiCategory {
  id: string;
  label: string;
  emojis: string[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = ${JSON.stringify(
  CATEGORIES.map((c) => ({ id: c.id, label: c.label, emojis: buckets[c.id] ?? [] })),
  null,
  2,
)};
`;

// Resolve relative to THIS script, not the caller's cwd, so the output
// always lands in cicchetto/src/keyboard regardless of where it's run.
const outPath = join(import.meta.dir, "../src/keyboard/emoji-data.ts");
await Bun.write(outPath, body);
console.log(`wrote ${outPath}`);
