defmodule Grappa.Accounts.User do
  @moduledoc """
  Operator-registered Grappa user.

  ## Identity

  Primary key is a binary UUID v4 (autogenerated). The bare `name` is
  the human-facing handle used at login; uniqueness is enforced both at
  the schema layer (`unique_constraint/2`) and at the DB layer
  (`users_name_index`). The format rule (`^[a-zA-Z][a-zA-Z0-9_-]*$`)
  restricts names to a shape that maps cleanly onto IRC nicknames and
  PubSub topic segments without escaping — Phase 2 onward uses
  `grappa:user:{name}` as the per-user PubSub topic.

  ## Password

  `password_hash` stores the Argon2id hash (parameters from
  `argon2_elixir` defaults; see `Grappa.Accounts` moduledoc for the
  rationale on why we don't override them in Phase 2). The `password`
  virtual field carries plaintext only between cast and changeset
  validation; it is `redact: true` so it never appears in logs or
  `inspect/1` output. Length bounds (8..256) are deliberately loose —
  password STRENGTH is the user's problem; password STORAGE is ours.
  """
  use Ecto.Schema
  import Ecto.Changeset

  @type t :: %__MODULE__{
          id: Ecto.UUID.t() | nil,
          name: String.t() | nil,
          password_hash: String.t() | nil,
          password: String.t() | nil,
          is_admin: boolean(),
          inserted_at: DateTime.t() | nil,
          updated_at: DateTime.t() | nil
        }

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "users" do
    field :name, :string
    field :password_hash, :string, redact: true
    field :password, :string, virtual: true, redact: true
    field :is_admin, :boolean, default: false

    timestamps(type: :utc_datetime_usec)
  end

  @name_format ~r/^[a-zA-Z][a-zA-Z0-9_\-]*$/

  @doc """
  Builds a create/update changeset.

  Required fields: `:name`, `:password`. The plaintext `:password` is
  hashed via Argon2 and stored as `:password_hash` only when the
  changeset is otherwise valid — invalid changesets short-circuit the
  CPU-heavy hash to keep the timing oracle on the Accounts side
  (`get_user_by_credentials/2`) rather than leaking validation cost
  through it.
  """
  @spec changeset(t(), map()) :: Ecto.Changeset.t()
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :password])
    |> validate_required([:name, :password])
    |> validate_length(:name, min: 1, max: 64)
    |> validate_format(:name, @name_format, message: "must start with a letter, then alphanumeric/_/-")
    |> validate_length(:password, min: 8, max: 256)
    |> unique_constraint(:name)
    |> put_password_hash()
  end

  @spec put_password_hash(Ecto.Changeset.t()) :: Ecto.Changeset.t()
  defp put_password_hash(%{valid?: true, changes: %{password: pw}} = cs),
    do: change(cs, password_hash: Argon2.hash_pwd_salt(pw))

  defp put_password_hash(cs), do: cs

  @doc """
  Narrow changeset for `:is_admin` toggles only. Separated from
  `changeset/2` because the latter is create-shaped (requires `:name`
  + `:password`); folding `:is_admin` in would either force callers to
  supply a password to flip a bit or require the create-changeset to
  make password optional. M cluster's `PATCH /admin/users/:id` admin
  endpoint and `bin/grappa create-user --admin` (Q-FIRST-ADMIN
  bootstrap path) both consume `Accounts.update_admin_flags/2`, which
  threads through this changeset.

  Casts `:is_admin` only; ignores any other key in `attrs` so a
  controller body can't sneak in `:name` / `:password_hash` /
  `:password` mutations via the admin endpoint.
  """
  @spec admin_changeset(t(), %{required(:is_admin) => boolean()}) :: Ecto.Changeset.t()
  def admin_changeset(%__MODULE__{} = user, attrs) do
    user
    |> cast(attrs, [:is_admin])
    |> validate_required([:is_admin])
  end

  @doc """
  Narrow changeset for password rotation (admin-panel bucket 2 —
  `PUT /admin/users/:id/password`). Same length bounds as
  `changeset/2` (8..256) but does NOT require `:name` — operator
  rotation doesn't ask for the existing name to be re-supplied.

  Casts `:password` only; ignores `:name`, `:is_admin`, etc. so the
  endpoint can't smuggle other field mutations through the
  password-only surface. The validity gate re-uses the same
  `put_password_hash/1` private the create changeset uses, so the
  hashing pipeline is single-sourced.
  """
  @spec password_changeset(t(), %{optional(:password) => String.t()}) :: Ecto.Changeset.t()
  def password_changeset(%__MODULE__{} = user, attrs) do
    # We require the operator to SUPPLY a `:password` key explicitly in
    # `attrs`. `validate_required([:password])` alone wouldn't catch a
    # missing key when `user.password` (virtual) carries a stale value
    # from a prior `cast/3` round-trip — Ecto's required-check passes
    # if the field is present in either changes OR data. Force the
    # check off the raw params keyset so the operator boundary stays
    # honest regardless of how `user` got materialized.
    user
    |> cast(attrs, [:password])
    |> validate_password_present(attrs)
    |> validate_length(:password, min: 8, max: 256)
    |> put_password_hash()
  end

  defp validate_password_present(changeset, attrs) do
    keys = attrs |> Map.keys() |> Enum.map(&to_string/1)

    if "password" in keys do
      changeset
    else
      add_error(changeset, :password, "can't be blank", validation: :required)
    end
  end
end
